version: '3'
services:
    app:
        container_name: cjournal-api
        restart: always
        build: .
        ports:
            - '8628:8628'
        links:
            - mongo
    mongo:
        container_name: mongo
        image: mongo
        ports:
            - '27017:27017'
