const express = require('express')
const router = express.Router()
const sqlite = require('sqlite3')
const db = new sqlite.Database('./db/trackers.db')
const errors = require('../helpers/errors')
const log = require('../helpers/logger')
const objectify = require('../helpers/objectify')
const stringSanitizer = require('../helpers/stringSanitizer')
const intSanitizer = require('../helpers/intSanitizer')
const { timestamp } = require('../helpers/timestamp')
const { saveFiles } = require('../middleware/saveFiles')
const validateActivity = require('../middleware/validateActivity')
const responses = require('../helpers/responses')

module.exports = router
